CREATE TABLE wind_turbines (
	turbine_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name TEXT,
	height DECIMAL NOT NULL,
	rotor_diameter DECIMAL NOT NULL,
	weight DECIMAL NOT NUll,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
