
CREATE TABLE sensors (
	sensor_id INTEGER GENERATED ALWAYS AS IDENTITY,
	turbine_id INTEGER NOT NULL REFERENCES wind_turbines(turbine_id) ON DELETE CASCADE,
	name TEXT,
	unit TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (turbine_id, sensor_id)
);
